<?php

return [
    "nganhang/list" => [
        "handler" => __DIR__ . "/../api/nganhang_list.php",
        "methods" => ["GET"],
        "auth" => true,
        "roles" => ["admin", "giangvien"],
    ],
    "nganhang/save" => [
        "handler" => __DIR__ . "/../api/nganhang_save.php",
        "methods" => ["POST", "PATCH"],
        "auth" => true,
        "roles" => ["admin", "giangvien"],
    ],
    "nganhang/delete" => [
        "handler" => __DIR__ . "/../api/nganhang_delete.php",
        "methods" => ["DELETE"],
        "auth" => true,
        "roles" => ["admin", "giangvien"],
    ],
    "nganhang/cauhoi/list" => [
        "handler" => __DIR__ . "/../api/nganhang_cauhoi_list.php",
        "methods" => ["GET"],
        "auth" => true,
        "roles" => ["admin", "giangvien"],
    ],
    "nganhang/cauhoi/save" => [
        "handler" => __DIR__ . "/../api/nganhang_cauhoi_save.php",
        "methods" => ["POST", "PATCH"],
        "auth" => true,
        "roles" => ["admin", "giangvien"],
    ],
    "nganhang/cauhoi/delete" => [
        "handler" => __DIR__ . "/../api/nganhang_cauhoi_delete.php",
        "methods" => ["DELETE"],
        "auth" => true,
        "roles" => ["admin", "giangvien"],
    ],
    "nganhang/import-word" => [
        "handler" => __DIR__ . "/../api/nganhang_import_word.php",
        "methods" => ["POST"],
        "auth" => true,
        "roles" => ["admin", "giangvien"],
    ],
    "profile/detail" => [
        "handler" => __DIR__ . "/../api/profile_detail.php",
        "methods" => ["GET"],
        "auth" => true,
        "roles" => ["admin", "giangvien"],
    ],
    "profile/update" => [
        "handler" => __DIR__ . "/../api/profile_update.php",
        "methods" => ["POST", "PATCH"],
        "auth" => true,
        "roles" => ["admin", "giangvien"],
    ],
    "nguoidung/list" => [
        "handler" => __DIR__ . "/../api/nguoidung_list.php",
        "methods" => ["GET"],
        "auth" => true,
        "roles" => ["admin"],
    ],
    "nguoidung/save" => [
        "handler" => __DIR__ . "/../api/nguoidung_save.php",
        "methods" => ["POST", "PATCH"],
        "auth" => true,
        "roles" => ["admin"],
    ],
    "nguoidung/delete" => [
        "handler" => __DIR__ . "/../api/nguoidung_delete.php",
        "methods" => ["DELETE"],
        "auth" => true,
        "roles" => ["admin"],
    ],
    "nguoidung/toggle-status" => [
        "handler" => __DIR__ . "/../api/nguoidung_toggle_status.php",
        "methods" => ["POST"],
        "auth" => true,
        "roles" => ["admin"],
    ],
    "monhoc/list" => [
        "handler" => __DIR__ . "/../api/monhoc_list.php",
        "methods" => ["GET"],
        "auth" => true,
        "roles" => ["admin", "giangvien"],
    ],
    "monhoc/save" => [
        "handler" => __DIR__ . "/../api/monhoc_save.php",
        "methods" => ["POST", "PATCH"],
        "auth" => true,
        "roles" => ["admin", "giangvien"],
    ],
    "monhoc/delete" => [
        "handler" => __DIR__ . "/../api/monhoc_delete.php",
        "methods" => ["DELETE"],
        "auth" => true,
        "roles" => ["admin", "giangvien"],
    ],
    "baithi/list" => [
        "handler" => __DIR__ . "/../api/baithi_list.php",
        "methods" => ["GET"],
        "auth" => true,
        "roles" => ["admin", "giangvien"],
    ],
    "baithi/save" => [
        "handler" => __DIR__ . "/../api/baithi_save.php",
        "methods" => ["POST", "PATCH"],
        "auth" => true,
        "roles" => ["admin", "giangvien"],
    ],
    "baithi/delete" => [
        "handler" => __DIR__ . "/../api/baithi_delete.php",
        "methods" => ["DELETE"],
        "auth" => true,
        "roles" => ["admin", "giangvien"],
    ],
    "cauhoi/list" => [
        "handler" => __DIR__ . "/../api/cauhoi_list.php",
        "methods" => ["GET"],
        "auth" => true,
        "roles" => ["admin", "giangvien"],
    ],
    "cauhoi/save" => [
        "handler" => __DIR__ . "/../api/cauhoi_save.php",
        "methods" => ["POST", "PATCH"],
        "auth" => true,
        "roles" => ["admin", "giangvien"],
    ],
    "cauhoi/import-word" => [
        "handler" => __DIR__ . "/../api/cauhoi_import_word.php",
        "methods" => ["POST"],
        "auth" => true,
        "roles" => ["admin", "giangvien"],
    ],
    "cauhoi/delete" => [
        "handler" => __DIR__ . "/../api/cauhoi_delete.php",
        "methods" => ["DELETE"],
        "auth" => true,
        "roles" => ["admin", "giangvien"],
    ],
    "cauhoi/import-bank" => [
        "handler" => __DIR__ . "/../api/cauhoi_import_bank.php",
        "methods" => ["POST"],
        "auth" => true,
        "roles" => ["admin", "giangvien"],
    ],
    "ketqua/export-excel" => [
        "handler" => __DIR__ . "/../api/ketqua_export_csv.php",
        "methods" => ["GET"],
        "auth" => true,
        "roles" => ["giangvien"],
    ],
    "lecturer/ketqua/summary" => [
        "handler" => __DIR__ . "/../api/ketqua_summary.php",
        "methods" => ["GET"],
        "auth" => true,
        "roles" => ["giangvien", "admin"],
    ],
    "lecturer/ketqua/submissions" => [
        "handler" => __DIR__ . "/../api/ketqua_submissions.php",
        "methods" => ["GET"],
        "auth" => true,
        "roles" => ["giangvien", "admin"],
    ],
    "lecturer/ketqua/detail" => [
        "handler" => __DIR__ . "/../api/ketqua_detail.php",
        "methods" => ["GET"],
        "auth" => true,
        "roles" => ["giangvien", "admin"],
    ],
    "login" => [
        "handler" => __DIR__ . "/../api/login.php",
        "methods" => ["POST"],
        "auth" => false,
    ],
    // --- THÍ SINH ROUTES ---
    "thisinh/dethi/list" => [
        "handler" => __DIR__ . "/../api/thisinh_dethi_list.php",
        "methods" => ["GET"],
        "auth" => true,
        "roles" => ["thisinh"],
    ],
    "thisinh/baithi/get_questions" => [
        "handler" => __DIR__ . "/../api/thisinh_baithi_questions.php",
        "methods" => ["GET"],
        "auth" => true,
        "roles" => ["thisinh"],
    ],
    "thisinh/baithi/submit" => [
        "handler" => __DIR__ . "/../api/thisinh_baithi_submit.php",
        "methods" => ["POST"],
        "auth" => true,
        "roles" => ["thisinh"],
    ],
    "thisinh/ketqua/list" => [
        "handler" => __DIR__ . "/../api/thisinh_ketqua_list.php",
        "methods" => ["GET"],
        "auth" => true,
        "roles" => ["thisinh"],
    ],
    "thisinh/profile/update" => [
        "handler" => __DIR__ . "/../api/profile_update.php",
        "methods" => ["POST", "PATCH"],
        "auth" => true,
        "roles" => ["thisinh", "giangvien", "admin"],
    ],
];
